### ISSUE TITLE
Import Error:  DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by BNNorman** [xoolive/quadtree#11]
This may be a result of the way I installed it and possibly the python version.

I'm using PyCharm with Anaconda3 (Python 3.6). "Conda install" didn't find smartquadtree. "Pip install"  didn't find a version either so I downloaded the egg (smartquadtree-1.0-py3.5-win32.egg) and used easy_install to install it. Easy install ended with error: Could not find suitable distribution for Requirement.parse('smartquadtree==1.0')

However, smartquadtree is listed in the installed packages within PyCharm (2017.3.3) so I thought I'd have a go at using it anyway since the smartquadtree folder in lib\site-packages contains smartquadtree.py and the pyd library.

Import fails: PyCharm underlines the "Quadtree" below.

from smartquadtree import Quadtree 

when the script is run it gives me an error:-

C:\ProgramData\Anaconda3\python.exe C:/Users/brian/PycharmProjects/PixelBot/TestQuadTree.py
Traceback (most recent call last):
  File "C:/Users/brian/PycharmProjects/PixelBot/TestQuadTree.py", line 1, in <module>
    from smartquadtree import Quadtree
  File "C:\ProgramData\Anaconda3\lib\site-packages\smartquadtree-1.0-py3.5-win32.egg\smartquadtree.py", line 7, in <module>
    __bootstrap__()
  File "C:\ProgramData\Anaconda3\lib\site-packages\smartquadtree-1.0-py3.5-win32.egg\smartquadtree.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
  File "C:\ProgramData\Anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: %1 is not a valid Win32 application.

My machine is Windows 10 64-bit.

I'm going to have a go at compiling your source code on my machine but if you can help me get past this problem I'd be grateful and this code is exactly what I need for a small educational simulator I'm working on.

Thanks for any help.
Regards
Brian

**Comment by xoolive** [comment]
pip doesn't find anything because there is nothing ready for windows 64 bits. You downloaded a 32 bits package to run on a 64 bits system which caused the error. 

Compilation with anaconda should be direct though with python setup.py install
